---
- name: "Choose which Windows updates to install"
  hosts: win
  tasks:
  - name: Choose which Windows updates to install
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups