---
- name: "Install multiple packages"
  hosts: win
  tasks:
  - name: Install multiple packages
    win_chocolatey:
      name: '{{ item }}'
      state: absent
    with_items:
    - procexp
    - putty
    - windirstat
